### ISSUE TITLE
去掉或者增加配置如 mongo,还有那个jar包

### ISSUE THREAD

**Issue by ljyljy0211** [Anoxia/noun#1]
去掉或者增加配置如 mongo,还有那个jar包

**Comment by anoxia** [comment]
> 去掉或者增加配置如 mongo,还有那个jar包

jar 包指的是？请把问题尽量描述清晰一些，赶紧快解决你的疑问。

**Comment by ljyljy0211** [comment]
额，我说的是readme
https://github.com/Anoxia/noun/tree/main/db
这里的readme写的和实际的脚本不太一致

就是是否安装 mongo、redis可以自配

**Comment by anoxia** [comment]
> 额，我说的是readme https://github.com/Anoxia/noun/tree/main/db 这里的readme写的和实际的脚本不太一致
> 
> 就是是否安装 mongo、redis可以自配

是的，这个目前是个架子，按需自己配
